### ISSUE TITLE
Cannot Launch Node

### ISSUE THREAD

**Issue by athtest800** [fsteinhardt/mpu6050_serial_to_imu#2]
Hi!
I get this error:
`ERROR: cannot launch node of type [mpu6050_serial_to_imu/mpu6050_serial_to_imu_node]: can't locate node [mpu6050_serial_to_imu_node] in package [mpu6050_serial_to_imu]
`
I use the `catkin_make_isolated --install --use-ninja`

Is there any solution?
Thank you!

**Comment by fsteinhardt** [comment]
I have just added the installation lines, please pull and try again.
