### ISSUE TITLE
The string::compare calling looks strange

### ISSUE THREAD

**Issue by chirping78** [fsteinhardt/mpu6050_serial_to_imu#3]
In mpu6050_serial_to_imu_node.cpp, there is a call:
```
input.compare(data_packet_start + 26, 2, "\n\r")
```
I do not know which platform do you run the test. Mac? or Linux?
Usually on Mac the text line end is '\n\r', and on Linux it's '\r\n'. 
But this converting is only done in "line discipline" layer. Here you are using "raw read", so I expect the cpp code will read the same thing that Arduino is sending. 
So it will read '\r\n' here, and the compare result is always NOT ZERO.

I guess the current code is working by accident, but not by your intent.

**Comment by fsteinhardt** [comment]
Thanks, the comparison code was wrong,  
fixed in commit f9010c3afdcd886aaa8b36e0dbe6629b23eb2c23
