### ISSUE TITLE
How to change it to work woth I2Cof Raspberry

### ISSUE THREAD

**Issue by Araas-Boloorchi** [fsteinhardt/mpu6050_serial_to_imu#6]
Hello, I am trying to get data just from raspberry pi for ROVIO would you tell me how to change it to get data from SCL and SDA of raspberry pi and send the trigger command by raspberry pi too.

**Comment by fsteinhardt** [comment]
This code is developed to run the imu interface on an arduino. If you want to use only an raspberry for your imu maybe try an raspberry ros package like https://github.com/matpalm/ros-mpu6050-node or https://github.com/chrisspen/ros_mpu6050_node .
